# Update submodules, build Docker image, and run a project build.
# This will run on every pull request to the 'devel' branch.
# NB: This does not push updates to submodules nor does it push
#     the built docker image to dockerhub

name: Build ARCS [TENTATIVE]

on:
  pull_request:
      branches: [ devel ]

jobs:
  build_image:
    name: Build ARCS image and project
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          ref: $GITHUB_REF

      - name: Update submodules
        run: git submodule update --remote

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build ARCS image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/arcs:latest

      - name: Run 'catkin build'
        run: make test
